title: Hi! I'm Cassie Adams
author: CassieAdams79
email: cassie.adams@okstate.edu
description: All about **me**
  I am in my final semester at OSU, working on my MBA with a Data Science focus.
  *Let's GO!!!*

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
